### ISSUE TITLE
ゲームの SendMessage が重い問題

### ISSUE THREAD

**Issue by mayoko** [mayoko/GAGame#11]
SendMessage が重いので, 改善したいんですが, 良さげな案が出たので書いときます

毎回の Update で, 小球が enemy にぶつかったら, その小球の id をリストに入れていく

Update の最後で, リストを参照していき, Die() を呼ぶ

**Comment by cexen** [comment]
実際やってないので想像で書くのですが，
現状 SendMessage は使用しておらず， transform.parent.getComponent で直接取得する方法をとってます．
想像した限り2つの謎があって，
- Updateの順番がわからない（どれが最後かわからない）
  - SCGameController.LateUpdate() で処理すればよい
- ワンチャン二度手間
  - 一般にFind系は重いので，衝突時に血縁関係を利用（しないと遅い）してリストを作ることになりそう
  - その時点で結局getComponentするはずなので現状と同じことになるのでは？
    - Player生成時にSCGameControllerがPlayerリストを抱えておけば再度取得しなくて済む
    - PlayerSphereにもgcとidを持たせておいてparent参照なしで直接gcに報告する
    - それってむしろ重くなるんじゃね？
    - そもそもGetComponentってそんなに重いか？

という感じの脳内会議になったんですがどうなんでしょう……．
