### ISSUE TITLE
GM: 「フレーム数」バーの問題

### ISSUE THREAD

**Issue by cexen** [mayoko/GAGame#12]
- param.playFrameの意味は，「フレーム数」ではなく「遺伝子の長さ」になりました．
  - 現在の仕様では，1遺伝子あたり5フレームの操作を支配するようになっています．
    - 表示を「遺伝子の長さ」とかそこらへんに修正するか，または
    - スライダーの横の表示値を実際の5倍にするといいのではなかろうか．
- 遺伝子の長さの上限を1000にしてほしい
  - スライダーが全体的に，永遠にゲームが終わらないようなオーダーになっちゃってるので……．

**Comment by cexen** [comment]
- 遺伝子の長さの下限も20にしてみてほしいです

**Comment by mayoko** [comment]
変えました
